-- ----------------------------
-- Records of blog_config
-- ----------------------------
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_TITLE', '我的个人博客', '1', '网站标题' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_TITLE');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_KEYWORDS', '个人博客,博客', '1', '网站关键词，关键字之间用,分隔' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_KEYWORDS');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_DESCRIPTION', '这是我的个人博客', '1', '网站描述' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_DESCRIPTION');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_URL', 'http://127.0.0.1:8080/', '1', '网站链接' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_URL');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_AUTHOR', 'admin', '1', '网站作者' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_AUTHOR');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_AVATAR', '/images/avatar.jpg', '1', '头像' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_AVATAR');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_NOTICE', '这是公告', '1', '公告' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_NOTICE');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'DEFAULT_IMAGE', '/images/default-preview.jpg', '1', '默认预览图' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'DEFAULT_IMAGE');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'AUTHOR_DESCRIPTION', '一二三四五，上山打老虎。', '1', '头像下的描述内容' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'AUTHOR_DESCRIPTION');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'FILING_ICP', null, '1', 'ICP备案' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'FILING_ICP');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'FILING_SECURITY', null, '1', '公安备案' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'FILING_SECURITY');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'COMMENT_CHECK', 'false', '2', '评论是否需要校检' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'COMMENT_CHECK');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BACKGROUND_LIST', '[\"/images/slide/background1.jpg\",\"/images/slide/background2.jpg\",\"/images/slide/background3.jpg\",\"/images/slide/background4.jpg\",\"/images/slide/background5.jpg\",\"/images/slide/background6.jpg\"]', '1', '网站的背景图片集合，格式为JSON数组' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BACKGROUND_LIST');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_HEAD', '<meta name=\"google-site-verification\" content=\"_-xMXp-rAz3pUIziyjcIoJ8D9VOV6yb7XrB5qaeq_Fg\" />\n<meta name=\"baidu-site-verification\" content=\"HsvFoNGZDC\" />\n<meta name=\"360-site-verification\" content=\"42179cf63604add68d1e11b26f44c322\" />\n<meta name=\"sogou_site_verification\" content=\"XvRe3wQaqS\"/>\n', '1', '博客头部插入的代码，如站点验证代码等' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_HEAD');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'BLOG_SCRIPT','<script>/*百度统计*/     var _hmt = _hmt || [];    (function() {        var hm = document.createElement(\"script\");        hm.src = \"https://hm.baidu.com/hm.js?77737a53e73e57c6c44b4640d1c108a1\";        var s = document.getElementsByTagName(\"script\")[0];        s.parentNode.insertBefore(hm, s);    })();</script>\n<script>/*百度自动推送*/  (function(){     var bp = document.createElement(\'script\');     var curProtocol = window.location.protocol.split(\':\')[0];     if (curProtocol === \'https\') {         bp.src = \'https://zz.bdstatic.com/linksubmit/push.js\';     }     else {         bp.src = \'http://push.zhanzhang.baidu.com/push.js\';     }     var s = document.getElementsByTagName(\"script\")[0];     s.parentNode.insertBefore(bp, s); })(); </script>\n<script>/*360自动收录*/ (function(){ var src = (document.location.protocol == \"http:\") ? \"http://js.passport.qihucdn.com/11.0.1.js?6396cb521d4daf069727dc8d995a3878\":\"https://jspassport.ssl.qhimg.com/11.0.1.js?6396cb521d4daf069727dc8d995a3878\"; document.write(\'<script src=\"\' + src + \'\" id=\"sozz\"><\\/script>\'); })(); </script>\n' , '1', '博客尾部插入的脚本，如统计代码、推送代码等' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'BLOG_SCRIPT');
INSERT INTO `blog_config`(`name`,`value`,`type`,`description`) SELECT 'FILE_STORAGE', '{\"aliyunAccessKeyId\":\"\",\"aliyunAccessKeySecret\":\"\",\"aliyunBucketName\":\"\",\"aliyunDomain\":\"\",\"aliyunEndPoint\":\"\",\"aliyunPrefix\":\"\",\"qcloudBucketName\":\"\",\"qcloudDomain\":\"\",\"qcloudPrefix\":\"\",\"qcloudSecretId\":\"\",\"qcloudSecretKey\":\"\",\"qiniuAccessKey\":\"\",\"qiniuBucketName\":\"\",\"qiniuDomain\":\"\",\"qiniuPrefix\":\"\",\"qiniuSecretKey\":\"\",\"localDirectory\":\"src/main/resources/static\",\"localDomain\":\"http://127.0.0.1:8080/\",\"type\":4,\"localPrefix\":\"upload\"}', '2', '云/本地存储配置信息' FROM DUAL WHERE NOT EXISTS(SELECT `name` FROM `blog_config` WHERE `name` = 'FILE_STORAGE');